### PR TITLE
Fix localization

### PR DESCRIPTION
**Pull request by itsumo2009**
OK.
I tried to fix long phrase

### CODE REVIEW

**Comment by pcfantasy** [comment]
Nice work.

But could you please do not change RealCity.csproj, add this in your gitignore file. Thanks.

**Comment by itsumo2009** [comment]
> float averageCitySalary = MainDataStore.citizenSalaryTotal / MainDataStore.citizenSalaryTotal;
> 
> should be
> 
> float averageCitySalary = MainDataStore.citizenSalaryTotal / MainDataStore.citizenCount;

Thank you

**Comment by pcfantasy** [comment]
@itsumo2009 

Can we find a better way to avoid modify RealCity.csproj? Do you have any suggestion?

**Comment by itsumo2009** [comment]
We can make csproj and sln autogenerated.

**Comment by itsumo2009** [comment]
Do you have any suggestion about info panel?

**Comment by pcfantasy** [comment]
@itsumo2009 
very cool feature!

I have move sln and csproj to ./VSPROJ (users need to copy these files to ../ to build their own env)

And in the main folder, gitignore is updated, so there will be no sln and csproj uploaded

**Pull request closed without merging**
